title: Quarrel Archival Project
description: >-
  Fan-made archival of Quarrel by Denki

url: "https://silvncr.github.io"
baseurl: "/quarrel"

remote_theme: "pages-themes/midnight@v0.2.0"
plugins:
- jekyll-remote-theme
